version: "3"

services:
  babylondnode0:
    container_name: babylondnode0
    image: "babylonlabs/babylond:v1.0.0-rc.3"
    command: >
      babylond --home /babylondhome start --log_format 'plain' 2>&1 | tee /babylondhome/babylond.log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ../.testnets/node0/babylond:/babylondhome:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  babylondnode1:
    container_name: babylondnode1
    image: "babylonlabs/babylond:v1.0.0-rc.3"
    command: >
      babylond --home /babylondhome start --log_format 'plain' 2>&1 | tee /babylondhome/babylond.log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - ../.testnets/node1/babylond:/babylondhome:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  faucet-backend:
    container_name: faucet-backend
    image: babylonchain/faucet-backend
    networks:
      localnet:
        ipv4_address: 192.168.10.4
    ports:
      - "3001:3001"
    volumes:
      - ../.testnets/faucet/config.yml:/app/config.yml
      - ../.testnets/faucet:/babylon
    depends_on:
      - babylondnode0
    restart: unless-stopped

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
