version: "3"

services:
  bitcoindsim:
    build:
      context: contrib/images/bitcoindsim/
      dockerfile: ./Dockerfile
    image: babylonlabs/bitcoindsim:latest
    platform: linux/amd64
    container_name: bitcoindsim
    networks:
      localnet:
        ipv4_address: 192.168.10.30
    environment:
      - ZMQ_SEQUENCE_PORT=29000
      - ZMQ_RAWBLOCK_PORT=29001
      - ZMQ_RAWTR_PORT=29002
      - RPC_PORT=18443
      - RPC_USER=rpcuser
      - RPC_PASS=rpcpass
      - WALLET_PASS=walletpass
      - WALLET_NAME=default
      - BTCSTAKER_WALLET_NAME=btcstaker
      - BTCSTAKER_WALLET_ADDR_COUNT=3
      - GENERATE_INTERVAL_SECS=10
    ports:
      - "18443:18443"
      - "29000-29002:29000-29002"

  btc-discord-faucet:
    container_name: btc-discord-faucet
    image: babylonlabs/btc-discord-faucet
    networks:
      localnet:
        ipv4_address: 192.168.10.4
    ports:
      - "3001:3001"
    volumes:
      - ../artifacts/faucet-config.yml:/app/config.yml
    depends_on:
      - bitcoindsim
    restart: unless-stopped

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
